name: readthedocs
dependencies:
  - python=3.7
  - pip
  - astropy
  - numpy
  - ipykernel
  - cython
  - matplotlib
  - pytest
  - scipy
  - requests
  - numpydoc
  - automake
  - pkg-config
  - cfitsio
  - libtool
