name: readthedocs
channels:
    - conda-forge
dependencies:
  - python=3.9
  - pip
  - astropy
  - numpy
  - ipykernel
  - cython
  - matplotlib
  - pytest
  - scipy
  - requests
  - numpydoc
  - automake
  - pkg-config
  - cfitsio
  - libtool
  - nbsphinx
